name: teddymccann
favicon: null
layout_spectrum: 0.9477819933090359
typography_spectrum: 0.678171087289229
title: Teddy McCann
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.31155664497055113
  lightness: 0.21451450139284134
  saturation: 0.7925941098947078
  rhythmicContrast: 0.007172352401539683
purpose: []
