name: teddymccann
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2509
title: Teddy McCann
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71855024-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffff00'
    - '#000000'
    - '#ffffff'
    - '#4d4d00'
    - '#939300'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
